# Generated by Django 4.0.2 on 2022-02-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarkari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarkari_name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=400)),
            ],
        ),
    ]
