# Generated by Django 3.2.8 on 2022-04-22 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220422_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
